### ISSUE TITLE
License for this repository

### ISSUE THREAD

**Issue by tesuji** [Skosulor/c8int#1]
Hi, I'm going to use your test room to check my interpreter, and add it to my repository. 
Do you have any license if I (and others) want to use it ?

If possible, could you upload a license file to this repository ?

**Comment by Skosulor** [comment]
Done!

**Comment by tesuji** [comment]
Hi, thank for the quick reply!
I see your update commit in 2bf982b4449f36d4f70c25912ef893383fa2196d .
That commit, however, is not a license to use the test rom.
It doesn't state which condition the test rom could be used, modified, distributed, used in commercial or not, etc.

You could use this site https://choosealicense.com/ to find a suitable license.

**Comment by Skosulor** [comment]
Accidentally created a new branch with the license instead of committing it, fixed no though.
