### ISSUE TITLE
Following behavior of COSMAC VIP for BNNN and not for `LD [I], VX`

### ISSUE THREAD

**Issue by tesuji** [Skosulor/c8int#2]
Firstly, I must thank you for your test rom. It helps me confident with my implementation.
Although, I have something to ask:

I ran your test rom (https://github.com/Skosulor/c8int/blob/master/test/c8_test.c8) through my own interpreter.
While your rom checks for behavior of BNNN instead of BXNN - just like COSMAC VIP chip-8 interpreter -
it doesn't increase `I` after `LD [I], Vx` or `LD Vx, [I]` instruction.
So the test rom reports that my implementation is wrong for `BNNN` (14 number displayed).

Is this behavior of your test rom expected?
It mismatches behavior of old COSMAC VIP for BNNN and not for `LD [I], VX`.

**Comment by Skosulor** [comment]
Hello, glad it helps!

I have not heard about the COSMAC VIP chip-8 interpreter and I'm not sure what you mean by that it doesn't increase `I` after `LD [I]`. 

The test is quite simple, it sets v0 to 4 and then calls a BNNN to jump forward 4 steps (NNN which is equal to current PC + V0).
If the jump would be shorter or just a step forward then the ROM will stop error checking and display number 14.

Have you tried stepping through the code as see what happens? In line 16 at https://github.com/Skosulor/c8int/blob/master/test/chip8_test.txt you can see the test for BNNN

**Comment by tesuji** [comment]
Hi, you could find info about behavior of `LD [I]` in this excellent guide <https://tobiasvl.github.io/blog/write-a-chip-8-emulator/#fx55-and-fx65-store-and-load-memory>, also in in Note (d section in wiki page: https://en.wikipedia.org/wiki/CHIP-8#Notes

> The test is quite simple, it sets v0 to 4 and then calls a BNNN to jump forward 4 steps (NNN which is equal to current PC + V0).
> If the jump would be shorter or just a step forward then the ROM will stop error checking and display number 14.

In my implementation, if I drop the statement to increase I to I + X + 1, the test rom displays OK string.

**Comment by Skosulor** [comment]
Oh i see what you mean now. The test rom was made for the modern take on chip8 interpreter so its not strange that it fails. It shouldn't display 14 though but the test rom can be wrong depending on how an instruction is implemented.

I don't think i will spend any time on fixing this but i will pin this issue for anyone else making an interpreter based on the one for the COSMAC and happens to stumble across my test rom.

**Comment by tesuji** [comment]
> The test rom was made for the modern take on chip8 interpreter so its not strange that it fails

Maybe my words were not clear. BNNN is a standard behavior of COSMAC VIP chip-8. BXNN is newer behavior on superchip and chip-48 interpreters.

> I don't think i will spend any time on fixing this but i will pin this issue for anyone else making an interpreter based on the one for the COSMAC and happens to stumble across my test rom.

That's understandable. Have a nice day!

P/S: Could you leave a respond for [my comment here](https://github.com/Skosulor/c8int/issues/1#issuecomment-772954308) about licensing stuffs?

**Comment by Skosulor** [comment]
I added a license in the root of the repository as well.
