### ISSUE TITLE
Test ROM Branching Issue

### ISSUE THREAD

**Issue by scgallagher** [Skosulor/c8int#3]
I've noticed an issue with test 11:
When verifying the carry flag for the first test, the instruction starting at 0xb2 (0x1300) jumps to address 0x100 instead of 0x192 like all of the other tests.  As a result, several tests are skipped and test 11 passes when it should fail.

I've verified that switching the instruction from 0x1300 to 0x1392 allows all of the tests to run.  I've pulled this repo and added the fix, but I don't have permission to push so I can open a PR.

Thanks for creating this awesome test rom, it's the most thorough I've found!
[testfix.zip](https://github.com/Skosulor/c8int/files/5992302/testfix.zip)

**Comment by Skosulor** [comment]
Hey Scgallagher, nice catch!

If you want to make a pull request you need to make a fork of the repo and commit the changes there first, check here for more
https://stackoverflow.com/questions/4384776/how-do-i-contribute-to-others-code-in-github

If you don't want to make the PR please notify me and I'll push the fix.

Cheers!

**Comment by scgallagher** [comment]
No problem, PR created.

Thanks again!

**Comment by Skosulor** [comment]
PR Accepted!

Cheers!
